/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/years/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Years */
        get: operations["app_api_year_api_get_all_years"];
        put?: never;
        /** Post Year */
        post: operations["app_api_year_api_post_year"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/years/{year_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Year By Id */
        get: operations["app_api_year_api_get_year_by_id"];
        put?: never;
        post?: never;
        /** Delete Year */
        delete: operations["app_api_year_api_delete_year"];
        options?: never;
        head?: never;
        /** Patch Year */
        patch: operations["app_api_year_api_patch_year"];
        trace?: never;
    };
    "/api/years/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Complete Year */
        post: operations["app_api_year_api_post_complete_year"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/months/{month_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Month By Id */
        get: operations["app_api_month_api_get_month_by_id"];
        put?: never;
        post?: never;
        /** Delete Month */
        delete: operations["app_api_month_api_delete_month"];
        options?: never;
        head?: never;
        /** Patch Month */
        patch: operations["app_api_month_api_patch_month"];
        trace?: never;
    };
    "/api/months/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Month */
        post: operations["app_api_month_api_post_month"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/months/year/{year_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Months In Year */
        get: operations["app_api_month_api_list_months_in_year"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Income
         * @description Get a list of all income records.
         */
        get: operations["app_api_income_api_list_income"];
        put?: never;
        /** Post Income */
        post: operations["app_api_income_api_post_income"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income/{income_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Income */
        delete: operations["app_api_income_api_delete_income"];
        options?: never;
        head?: never;
        /** Patch Income */
        patch: operations["app_api_income_api_patch_income"];
        trace?: never;
    };
    "/api/variable-expense/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Variable Expense
         * @description List all variable expenses based on filters
         */
        get: operations["app_api_variable_expense_api_list_variable_expense"];
        put?: never;
        /** Post Variable Expense */
        post: operations["app_api_variable_expense_api_post_variable_expense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variable-expense/{variable_expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Variable Expense */
        delete: operations["app_api_variable_expense_api_delete_variable_expense"];
        options?: never;
        head?: never;
        /** Patch Variable Expense */
        patch: operations["app_api_variable_expense_api_patch_variable_expense"];
        trace?: never;
    };
    "/api/fixed-expense/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Fixed Expense
         * @description List all fixed expenses based on filters
         */
        get: operations["app_api_fixed_expense_api_list_fixed_expense"];
        put?: never;
        /** Post Fixed Expense */
        post: operations["app_api_fixed_expense_api_post_fixed_expense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-expense/{fixed_expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fixed Expense */
        delete: operations["app_api_fixed_expense_api_delete_fixed_expense"];
        options?: never;
        head?: never;
        /** Patch Fixed Expense */
        patch: operations["app_api_fixed_expense_api_patch_fixed_expense"];
        trace?: never;
    };
    "/api/savings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Savings */
        get: operations["app_api_savings_api_get_all_savings"];
        put?: never;
        /** Post Savings */
        post: operations["app_api_savings_api_post_savings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/savings/{savings_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Savings By Id */
        get: operations["app_api_savings_api_get_savings_by_id"];
        put?: never;
        post?: never;
        /** Delete Savings */
        delete: operations["app_api_savings_api_delete_savings"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Transaction List
         * @description Uploads a CSV file, parses it, and inserts transactions into the database.
         */
        post: operations["app_api_transaction_api_upload_transaction_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["app_api_transaction_api_list_transactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction By Id */
        get: operations["app_api_transaction_api_get_transaction_by_id"];
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["app_api_transaction_api_delete_transaction"];
        options?: never;
        head?: never;
        /** Patch Transaction */
        patch: operations["app_api_transaction_api_patch_transaction"];
        trace?: never;
    };
    "/api/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Transaction */
        post: operations["app_api_transaction_api_post_transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/years-months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Time Data */
        get: operations["app_api_time_api_list_all_time_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** YearOutSchema */
        YearOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Year */
            year: string;
        };
        /** YearInSchema */
        YearInSchema: {
            /** Year */
            year: string;
        };
        /** MonthOutSchema */
        MonthOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Month */
            month: string;
            year: components["schemas"]["YearSchema"];
        };
        /** YearSchema */
        YearSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Year */
            year: string;
        };
        /** MonthInSchema */
        MonthInSchema: {
            /** Month */
            month: string;
        };
        /** IncomeFilterSchema */
        IncomeFilterSchema: {
            /** Name */
            name?: string | null;
            /** Date */
            date?: string | null;
            /** Expected */
            expected?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** IncomeOutSchema */
        IncomeOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Expected */
            expected: number;
            /** Actual */
            actual: number;
            month: components["schemas"]["MonthSchema"];
        };
        /** MonthSchema */
        MonthSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Month */
            month: string;
            year: components["schemas"]["YearSchema"];
        };
        /** IncomeInSchema */
        IncomeInSchema: {
            /** Name */
            name?: string | null;
            /** Date */
            date?: string | null;
            /** Expected */
            expected?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** VariableExpenseFilterSchema */
        VariableExpenseFilterSchema: {
            /** Name */
            name?: string | null;
            /** Budget */
            budget?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** VariableExpenseOutSchema */
        VariableExpenseOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Budget */
            budget: number;
            /** Actual */
            actual: number;
            month: components["schemas"]["MonthSchema"];
        };
        /** VariableExpenseInSchema */
        VariableExpenseInSchema: {
            /** Name */
            name?: string | null;
            /** Budget */
            budget?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** FixedExpenseFilterSchema */
        FixedExpenseFilterSchema: {
            /** Name */
            name?: string | null;
            /** Due */
            due?: string | null;
            /** Budget */
            budget?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** FixedExpenseOutSchema */
        FixedExpenseOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Due
             * Format: date
             */
            due: string;
            /** Budget */
            budget: number;
            /** Actual */
            actual: number;
            month: components["schemas"]["MonthSchema"];
        };
        /** FixedExpenseInSchema */
        FixedExpenseInSchema: {
            /** Name */
            name?: string | null;
            /** Due */
            due?: string | null;
            /** Budget */
            budget?: number | null;
            /** Actual */
            actual?: number | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** SavingsOutSchema */
        SavingsOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Budget */
            budget: number;
            /** Actual */
            actual: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            month: components["schemas"]["MonthSchema"];
        };
        /** SavingsInSchema */
        SavingsInSchema: {
            /** Name */
            name: string;
            /** Budget */
            budget: number;
            /** Actual */
            actual: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Month */
            month: string;
        };
        /** TransactionFilterSchema */
        TransactionFilterSchema: {
            /** Date */
            date?: string | null;
            /** Amount */
            amount?: number | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Month Id */
            month_id?: string | null;
        };
        /** TransactionOutSchema */
        TransactionOutSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Description */
            description: string;
            /** Category */
            category: string;
            month: components["schemas"]["MonthSchema"];
        };
        /** TransactionInSchema */
        TransactionInSchema: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Description */
            description: string;
            /** Category */
            category: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    app_api_year_api_get_all_years: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearOutSchema"][];
                };
            };
        };
    };
    app_api_year_api_post_year: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearOutSchema"];
                };
            };
        };
    };
    app_api_year_api_get_year_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearOutSchema"];
                };
            };
        };
    };
    app_api_year_api_delete_year: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_year_api_patch_year: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearOutSchema"];
                };
            };
        };
    };
    app_api_year_api_post_complete_year: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearOutSchema"];
                };
            };
        };
    };
    app_api_month_api_get_month_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthOutSchema"];
                };
            };
        };
    };
    app_api_month_api_delete_month: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_month_api_patch_month: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                month_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthOutSchema"];
                };
            };
        };
    };
    app_api_month_api_post_month: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonthInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthOutSchema"];
                };
            };
        };
    };
    app_api_month_api_list_months_in_year: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthOutSchema"][];
                };
            };
        };
    };
    app_api_income_api_list_income: {
        parameters: {
            query?: {
                name?: string | null;
                date?: string | null;
                expected?: number | null;
                actual?: number | null;
                month_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeOutSchema"][];
                };
            };
        };
    };
    app_api_income_api_post_income: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeOutSchema"];
                };
            };
        };
    };
    app_api_income_api_delete_income: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_income_api_patch_income: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeOutSchema"];
                };
            };
        };
    };
    app_api_variable_expense_api_list_variable_expense: {
        parameters: {
            query?: {
                name?: string | null;
                budget?: number | null;
                actual?: number | null;
                month_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableExpenseOutSchema"][];
                };
            };
        };
    };
    app_api_variable_expense_api_post_variable_expense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableExpenseInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableExpenseOutSchema"];
                };
            };
        };
    };
    app_api_variable_expense_api_delete_variable_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variable_expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_variable_expense_api_patch_variable_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variable_expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariableExpenseInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariableExpenseOutSchema"];
                };
            };
        };
    };
    app_api_fixed_expense_api_list_fixed_expense: {
        parameters: {
            query?: {
                name?: string | null;
                due?: string | null;
                budget?: number | null;
                actual?: number | null;
                month_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedExpenseOutSchema"][];
                };
            };
        };
    };
    app_api_fixed_expense_api_post_fixed_expense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixedExpenseInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedExpenseOutSchema"];
                };
            };
        };
    };
    app_api_fixed_expense_api_delete_fixed_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixed_expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_fixed_expense_api_patch_fixed_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixed_expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixedExpenseInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedExpenseOutSchema"];
                };
            };
        };
    };
    app_api_savings_api_get_all_savings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsOutSchema"][];
                };
            };
        };
    };
    app_api_savings_api_post_savings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavingsInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsOutSchema"];
                };
            };
        };
    };
    app_api_savings_api_get_savings_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                savings_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavingsOutSchema"];
                };
            };
        };
    };
    app_api_savings_api_delete_savings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                savings_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_transaction_api_upload_transaction_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Month Id
                     * Format: uuid
                     */
                    month_id: string;
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_transaction_api_list_transactions: {
        parameters: {
            query?: {
                date?: string | null;
                amount?: number | null;
                description?: string | null;
                category?: string | null;
                month_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOutSchema"][];
                };
            };
        };
    };
    app_api_transaction_api_get_transaction_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOutSchema"];
                };
            };
        };
    };
    app_api_transaction_api_delete_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    app_api_transaction_api_patch_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOutSchema"];
                };
            };
        };
    };
    app_api_transaction_api_post_transaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOutSchema"];
                };
            };
        };
    };
    app_api_time_api_list_all_time_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
