import React from "react";
import type { Metadata } from "next";
import "./globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import TitleBar from "@/components/TitleBar";
import { ToastProvider } from "@/components/ToastSystem";

export const metadata: Metadata = {
    title: "Budget Buddy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <html lang="en">
            <body
                className='content'
            >
                <TitleBar />
                <div>
                    <ToastProvider>
                        {children}
                    </ToastProvider>
                </div>
            </body>
        </html>
    );
}
