import React from "react";
import type { Metadata } from "next";
import "./globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastProvider } from "@/components/ToastSystem";
import TitleBar from "@/components/TitleBar";

export const metadata: Metadata = {
    title: "Budget Buddy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
        children: React.ReactNode;
    }>) {

    return (
        <html lang="en">
            <body
                className='content'
            >
                {children}
            </body>
        </html>
    );
}
